### ISSUE TITLE
Can't visit profile page using URL

### ISSUE THREAD

**Issue by maharshmellow** [CMPUT404W20/CMPUT404-project-socialdistribution#148]
When trying to visit http://127.0.0.1:8000/profile/USERNAME from the homepage, it doesn't work, but when clicking the profile button, it works, even though it's the same URL. So this issue might have something to do with the router and the `location` object passed to the ProfilePage.

**Steps to reproduce**
1) `yarn build`
2) `python manage.py runserver`
3) Visit 127.0.0.1:8000
4) Log in 
5) Visit http://127.0.0.1:8000/profile/USERNAME

I get a blank page here and the following error.

![Screen Shot 2020-03-21 at 1 32 57 AM](https://user-images.githubusercontent.com/4590693/77221918-f3611d00-6b13-11ea-8296-e872681831f4.png)

**Comment by ceciliaccwei** [comment]
I've been trying to fix this and it seems that it's out of my hand.
Basically when viewing a profile, I need to use two parameters.
1. Current user id -> retrieve from local storage
2. The user id of this user profile -> get from the previous page where the user would click on something that has this person's id stored.
If viewing directly from the url, then there's no way i can get the id of this person. I checked the behaviour of linkedin, the user gets to define their **unique** profile page url. 
Two possible solution here: 
1. instead of using profile/username, use profile/id, say profile/https://cmput404-socialdistribution.herokuapp.com/author/1
pro: the user id can be retrieved from the url
con: url will be massive and looks weird
2. leave this for now since its not part of the requirements...

**Comment by maharshmellow** [comment]
@ceciliaccwei Ok sure we can just leave this for now. I was thinking it would be an issue since we need the user to be able to access profile pages of other users but we can just hope that no one will type in the url and just use the UI to access it 😄

**Comment by ceciliaccwei** [comment]
Once we finish the search function, the user should be able to see those users he wants to find and access their profile page from there. Hope this will be fine😄
