### ISSUE TITLE
Use the React Context to store user information

### ISSUE THREAD

**Issue by maharshmellow** [CMPUT404W20/CMPUT404-project-socialdistribution#164]
Currently we use the localstorage to store the userid and username. But some endpoints require us to send the entire author object and ideally we don't want to store everything in localstorage. React provides Contexts that can be used to store this type of information and use it in other places. It acts like a global state in a way where we can store all the user related information. 

https://alligator.io/react/manage-user-login-react-context/

**Comment by ceciliaccwei** [comment]
It works like a global props but in the meantime it is hard to retrieve the context outside of the render function, e.g. setState. Combining all the links below, I updated our Router so that it pass the context(current user object) to the routed components😄
https://alligator.io/react/manage-user-login-react-context/
https://auth0.com/blog/handling-authentication-in-react-with-context-and-hooks/
https://stackoverflow.com/questions/49870098/how-to-get-the-data-from-react-context-consumer-outside-the-render
https://icetutor.com/question/access-react-context-outside-of-render-function/
Aight, time for bed🌛

**Comment by maharshmellow** [comment]
> Aight, time for bed🌛

AHHAHA stayed up so late omg
